signin-prom-ui:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 100m
        memory: 150Mi
      requests:
        cpu: 50m
        memory: 100Mi

    env:
      - name: HTTP_PORT
        value: "80"

      - name: PORT
        value: "80"

      - name: API_PATH
        value: "https://user-services-dev.prom.co.th"

      - name: AUTH_CLIENT_ID
        value: "dummy"

      - name: AUTH_ENDPOINT
        value: "https://user-services-dev.prom.co.th/api/Authentication/org/default/action/Login"

      - name: AUTH_CLIENT_SECRET #API key for SSO API
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: SSO_AUTH_API_KEY1

      - name: IDP_ENDPOINT
        value: "https://user-services-dev.prom.co.th/api/IDP/org/default/action/"

      - name: ADMIN_PAGE
        value: "https://dev.prom.co.th/"
