signin-prom-ui:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 100m
        memory: 150Mi
      requests:
        cpu: 50m
        memory: 100Mi

    env:
      - name: HTTP_PORT
        value: "80"

      - name: PORT
        value: "80"

      - name: API_PATH
        value: "https://user-services-dev.prom.co.th"
