---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: app-secrets
spec:
  refreshInterval: 10m0s      # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store     # name of the SecretStore (or kind specified)
  target:
    name: app-secrets  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: "KEYCLOAK_CREDENTIAL"
      remoteRef:
        key: initial-secret
        version: latest
        property: KEYCLOAK_CREDENTIAL
