apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP  
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 10k
spec:
  tls:
    - hosts:
      - {{ .Values.domainKeycloak }}
      secretName: keycloak-cert
  rules:
    - host: {{ .Values.domainKeycloak }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak-http
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ing-2
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP  
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 10k
spec:
  tls:
    - hosts:
      - {{ .Values.domainKeycloak2 }}
      secretName: keycloak-cert-2
  rules:
    - host: {{ .Values.domainKeycloak2 }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak-http
                port:
                  number: 80
