---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: keycloak-credential
spec:
  refreshInterval: 1m          # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store     # name of the SecretStore (or kind specified)
  target:
    name: keycloak-credential  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: "keycloak-user"
      remoteRef:
        key: initial-secret
        version: latest
        property: KEYCLOAK_USER

    - secretKey: "keycloak-password" 
      remoteRef:
        key: initial-secret
        version: latest
        property: KEYCLOAK_PASSWORD
