apiVersion: v2
name: helm-promid
description: A Helm chart for PromID

type: application

version: 1.0.0

appVersion: "1.0"

dependencies:
  - name: keycloak
    version: 18.4.3
    repository: https://codecentric.github.io/helm-charts
    condition: keycloak.enabled
