envAlias: production
domainKeycloak: keycloak.promid.prom.co.th
domainPromIDWeb: promid.prom.co.th
domainKonga: konga.promid.prom.co.th
domainKong: api.promid.prom.co.th
domainPgAdmin: pgweb.promid.prom.co.th

promid-api:
  ingress:
    enabled: false

  pods:
    env:
      # To solve ulimit(128) issue
      - name: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"

      - name: JAEGER_AGENT_HOST
        value: "http://tempo.tempo.svc.cluster.local"

      - name: JAEGER_AGENT_PORT
        value: "4317"

      - name: Keycloak__realm
        value: "Test"

      - name: Keycloak__auth-server-url
        value: "http://keycloak-http/"

      - name: Keycloak__resource
        value: "test-client"

      - name: Keycloak__credentials__secret
        valueFrom:
          secretKeyRef:
            name: app-secrets
            key: KEYCLOAK_CREDENTIAL
            optional: false

promid-web:
  ingress:
    enabled: false

  pods:
    env:
      # To solve ulimit(128) issue
      - name: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"