apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: idp-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: idp-secret            # name of the k8s Secret to be created
  data:
  # Keycloak authenticiation
  - secretKey: SSO_IDP_CLIENT_ID
    remoteRef:
      key: initial-secret
      property: SSO_IDP_CLIENT_ID
      
  - secretKey: SSO_IDP_CLIENT_SECRET
    remoteRef:
      key: initial-secret
      property: SSO_IDP_CLIENT_SECRET

  - secretKey: SSO_IDP_ENDPOINT
    remoteRef:
      key: initial-secret
      property: SSO_IDP_ENDPOINT

  # Keycloak add user, reset user's password
  - secretKey: SSO_ADMIN_IDP_CLIENT_ID
    remoteRef:
      key: initial-secret
      property: SSO_ADMIN_IDP_CLIENT_ID
      
  - secretKey: SSO_ADMIN_IDP_CLIENT_SECRET
    remoteRef:
      key: initial-secret
      property: SSO_ADMIN_IDP_CLIENT_SECRET

  - secretKey: SSO_ADMIN_IDP_ENDPOINT
    remoteRef:
      key: initial-secret
      property: SSO_ADMIN_IDP_ENDPOINT

  - secretKey: SSO_ADMIN_IDP_REALM
    remoteRef:
      key: initial-secret
      property: SSO_ADMIN_IDP_REALM
