sso-api-service:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 100m
        memory: 150Mi
      requests:
        cpu: 50m
        memory: 100Mi

    env:
      - name: HTTP_PORT
        value: "80"

      - name: PORT
        value: "80"

      # To solve ulimit(128) issue
      - name: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"

      - name: ASPNETCORE_ENVIRONMENT
        value: "Development"

      - name: IsDev
        value: "true"

      - name: PostgreSQL__Host
        value: "postgresql-promid"

      - name: PostgreSQL__Database
        value: "promid"

      - name: PostgreSQL__User
        value: "postgres"

      - name: PostgreSQL__Password
        valueFrom:
          secretKeyRef:
            name: promid-postgres-secret
            key: adminPasswordKey
            optional: false

      # JWT validation with Keycloak
      - name: SSO__issuer
        value: "https://keycloak.promid.prom.co.th/auth/realms/promid-nonprod"

      - name: SSO__signedKeyUrl
        value: "https://keycloak.promid.prom.co.th/auth/realms/promid-nonprod/protocol/openid-connect/certs"

      # Authentitication with Keycloak
      - name: IDP_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: SSO_IDP_CLIENT_ID

      - name: IDP_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: SSO_IDP_CLIENT_SECRET

      - name: IDP_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: SSO_IDP_ENDPOINT

      # User management with Keycloak
      - name: ADMIN_IDP_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: SSO_ADMIN_IDP_CLIENT_ID

      - name: ADMIN_IDP_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: SSO_ADMIN_IDP_CLIENT_SECRET

      - name: ADMIN_IDP_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: SSO_ADMIN_IDP_ENDPOINT

      - name: ADMIN_IDP_REALM
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: SSO_ADMIN_IDP_REALM

      # Email
      - name: EMAIL_ID
        valueFrom:
          secretKeyRef:
            name: email-secret
            key: EMAIL_ID

      - name: EMAIL_KEY
        valueFrom:
          secretKeyRef:
            name: email-secret
            key: EMAIL_KEY
