sso-api-service:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 100m
        memory: 150Mi
      requests:
        cpu: 50m
        memory: 100Mi

    env:
      - name: PORT
        value: "80"

      - name: HTTP_PORT
        value: "80"

      # To solve ulimit(128) issue
      - name: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"

      - name: ASPNETCORE_ENVIRONMENT
        value: "Production"

      - name: IsDev
        value: "false"

      - name: PostgreSQL__Host
        value: "postgresql-promid"

      - name: PostgreSQL__Database
        value: "promid"

      - name: PostgreSQL__User
        value: "postgres"

      - name: PostgreSQL__Password
        valueFrom:
          secretKeyRef:
            name: promid-postgres-secret
            key: adminPasswordKey
            optional: false

      - name: SSO__issuer
        value: "https://keycloak.promid.prom.co.th/auth/realms/promid"

      - name: SSO__signedKeyUrl
        value: "https://keycloak.promid.prom.co.th/auth/realms/promid/protocol/openid-connect/certs"
