
app-api-service:
  enabled: true
  nameOverride: app-api-service

  ingress:
    enabled: false

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment

    image:
      name: asia-southeast1-docker.pkg.dev/promrub-personal-use/promid/app-api-service

  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
        name: http
